export { AboutSection } from './AboutSection'
export { CustomerServiceSection } from './CustomerServiceSection'
export { FooterSection } from './FooterSection'
export { HeaderSection } from './HeaderSection'
export { HeroSection } from './HeroSection'
export { LocationContactSection } from './LocationContactSection'
export { ProductsSection } from './ProductsSection'
export { TeamSection } from './TeamSection'
